[[schema]]
name = "ADR"
config_version = "1.2"
file_patterns = [
  "ADRs/ADR-*.md",
  "ADR-AI/ADR-AI-*.md"
]

[schema.new]
id_generator = { strategy = "increment", prefix = "ADR-", padding = 3 }
filename_template = "{{id}}-{{title|kebab-case}}.md"
output_path = ["docs/RAG/ADRs"]

[schema.frontmatter]
user_frontmatter = [
  "id",
  "tags",
  "status",
  "depends_on",
  "created_date",
  "last_modified",
  "related_files"
]

[schema.frontmatter.edges]
graph_edges = ["depends_on"]

[schema.validate]
severity = "error"

[schema.validate.edges.depends_on]
required = "warning"
