[[schema]]
name = "EPIC"
config_version = "1.2"
file_patterns = [
  "AI-EPIC/AI-EPIC-*.md"
]

[schema.new]
id_generator = { strategy = "increment", prefix = "AI-EPIC-", padding = 3 }
filename_template = "{{id}}-{{title|kebab-case}}.md"
output_path = ["docs/RAG/AI-EPIC"]

[schema.frontmatter]
user_frontmatter = [
  "node_id",
  "tags",
  "kanban_status",
  "date_created",
  "date_completed",
  "AI_IMP_spawned"
]

[schema.frontmatter.gtd]
kanban_status = [
  "backlog",
  "planned",
  "in-progress",
  "completed",
  "cancelled"
]
kanban_statusline = true

[schema.validate]
severity = "error"
